# Run docker-compose build
# Run docker-compose up
# Live long and prosper

version: '3.1'
services:
  apache:
    build: .docker/apache
    container_name: sf4_apache
    ports:
      - "82:80"
    volumes:
      - .docker/config/vhosts/sf4.conf:/usr/local/apache2/conf/extra/httpd-vhosts.conf
      - ${SYMFONY_APP}:/usr/local/apache2/htdocs
    depends_on:
      - php

  mysql:
    image: mysql:5.7
    container_name: sf4_mysql
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  php:
    build: .docker/php
    container_name: sf4_php
    volumes:
      - ${SYMFONY_APP}:/usr/local/apache2/htdocs
    depends_on:
      - mysql

  nginx:
    container_name: angular_nginx
    build: .docker/nginx
    volumes:
      - ${ANGULAR_APP}/dist/angular:/usr/share/nginx/html
    ports:
      - "81:80"
      - "443:443"

  node:
    build: .docker/node
    container_name: angular_node
    ports:
      - "4200:4200"
    volumes:
      - ${ANGULAR_APP}:/home/node/app/frontend
    tty: true
    command:
      - /bin/sh
      - -c
      - |
        cd /home/node/app/frontend && npm start

volumes:
  mysqldata:
